### ISSUE TITLE
Better Error Handling

### ISSUE THREAD

**Issue by wucherpfennig** [PrestaShop/PrestaShop-webservice-lib#77]
Dear all

We are using your webservice library very frequently and it is mostly running great.

With mostly I mean until you get some weird exception thrown. Even if you want to catch the exception (which works) there is no use to do so as the function ```checkStatusCode``` basically destroys  all information **received** by the bad api call / from the webservice.

Did you ever suggest to rework error handling? at least let us throw some decent exceptions which could be helpful to debug...

BR wucherpfennig

**Comment by gplanchat** [comment]
I am working on a pull request, implementing this exception hierarchy:

The `PrestaShopWebserviceException` exception class becomes an interface extending `\Throwable` when available (PHP 7.0+)

* `PrestaShopWebserviceBadParametersException` extends `\InvalidArgumentException` and implements `PrestaShopWebserviceException`
* `PrestaShopWebserviceMissingPreconditionException` extends `\BadFunctionCallException` and implements `PrestaShopWebserviceException`
* `PrestaShopWebserviceBadRequestException` extends `\RuntimeException` and implements `PrestaShopWebserviceException` for HTTP 400 responses
* `PrestaShopWebserviceUnauthorizedException` extends `\RuntimeException` and implements `PrestaShopWebserviceException` for HTTP 401 responses
* `PrestaShopWebserviceForbiddenException` extends `\RuntimeException` and implements `PrestaShopWebserviceException` for HTTP 403 responses
* `PrestaShopWebserviceNotFoundException` extends `\RuntimeException` and implements `PrestaShopWebserviceException` for HTTP 404 responses
* `PrestaShopWebserviceMethodNotAllowedException` extends `\RuntimeException` and implements `PrestaShopWebserviceException` for HTTP 405 responses
* `PrestaShopWebserviceServerException` extends `\RuntimeException` and implements `PrestaShopWebserviceException` for HTTP 5xx responses

Doing this way, in the code already using the library, when you have a `catch (PrestaShopWebserviceException $exception)`, the exception will still be catched and the `$exception` variable will still contain everything you previously had.

**Comment by matks** [comment]
As initial topic was answered I close this issue.

For the record, this webservice client does not have extensive features because it's a SDK with no big ambitions
