### ISSUE TITLE
Question about "&date=1"

### ISSUE THREAD

**Issue by clemzarch** [PrestaShop/PrestaShop-webservice-lib#90]
Hello, does anyone know if it's safe to **always** set the parameter `&date=1`?
I know it's a workaround for a bug when using date filters, but I'm tempted to always leave it on in my code, no matter the resource, so I never have to worry about it.

Do we know if leaving it to `1` could break some resources or results?
And by the way, I only know of this workaround from forums and GitHub issues ([here](https://www.prestashop.com/forums/topic/101502-webservice-api-filter-for-date-ranges/) and [here](https://github.com/PrestaShop/PrestaShop/issues/10822#issuecomment-426565679)), but is it written somewhere in the documentation?

**Comment by matks** [comment]
Hello,

My apologies, it seems this repository was misconfigured. [A long time ago](https://build.prestashop-project.org/news/2018/moving-issues-to-github/) we decided to gather every problem about PrestaShop in the Core repository. For every problem, about every repository in the project, they should be put on the Core repository https://github.com/PrestaShop/prestaShop/ here: https://github.com/PrestaShop/PrestaShop/issues/new/choose

To enforce this, we closed the ability to open an issue on every other repository... but it seems we forgot this one.

I will fix this by closing this repository "Issues" section and add a notice in the README.

You could re-submit your question here https://github.com/PrestaShop/PrestaShop/discussions
