### ISSUE TITLE
PSWS-Version response header case sensitivity

### ISSUE THREAD

**Issue by rsobap** [PrestaShop/PrestaShop-webservice-lib#94]
It seems that some web servers return this header in lowercase. This causes the version compatibility check to be ignored because the library expects the header to be exactly 'PSWS-Version':
https://github.com/PrestaShop/PrestaShop-webservice-lib/blob/94feb5f547b4a33cd9c759edfa581f30fa42803b/PSWebServiceLibrary.php#L214

Example response:

```
HTTP/1.1 200 OK
Connection: Keep-Alive
Keep-Alive: timeout=5, max=100
access-time: 1701712674
x-powered-by: PrestaShop Webservice
psws-version: 8.1.2
content-type: text/xml;charset=utf-8
execution-time: 0.005
...
server: LiteSpeed
vary: User-Agent
```

**Comment by matks** [comment]
Hi @rsobap I submitted a PR to fix this https://github.com/PrestaShop/PrestaShop-webservice-lib/pull/99/

It seems this repository was misconfigured. [A long time ago](https://build.prestashop-project.org/news/2018/moving-issues-to-github/) we decided to gather every problem about PrestaShop in the Core repository. For every problem, about every repository in the project, they should be put on the Core repository https://github.com/PrestaShop/prestaShop/ here: https://github.com/PrestaShop/PrestaShop/issues/new/choose

To enforce this, we closed the ability to open an issue on every other repository... but it seems we forgot this one.

I will fix this by closing this repository "Issues" section and add a notice in the README.
