### ISSUE TITLE
Error: In separating headers and response body

### ISSUE THREAD

**Issue by innamhunzai** [PrestaShop/PrestaShop-webservice-lib#95]
We are using PS webserice library for our data syncing processes.  While doing put|post requests the library raises exception at this line: https://github.com/PrestaShop/PrestaShop-webservice-lib/blob/94feb5f547b4a33cd9c759edfa581f30fa42803b/PSWebServiceLibrary.php#L197 

Upon debugging we found this line of code to calculate the size of headers:
https://github.com/PrestaShop/PrestaShop-webservice-lib/blob/94feb5f547b4a33cd9c759edfa581f30fa42803b/PSWebServiceLibrary.php#L195

We have php 7.4 and Apache Server in place. and we believe the parsing of headers and response body is not proper way for all types of servers.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop-webservice-lib/pull/96
